default_platform(:ios)

platform :ios do
  desc "Build the app"
  lane :build do
    xcodebuild(
      workspace: "MineOpsCompanion.xcworkspace",
      scheme: "MineOpsCompanion",
      configuration: "Debug",
      build: true,
      destination: "platform=iOS Simulator,name=iPhone 16,OS=18.0",
      xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO"
    )
  end

  desc "Run tests"
  lane :test do
    run_tests(
      workspace: "MineOpsCompanion.xcworkspace",
      scheme: "MineOpsCompanion",
      testplan: "MineOpsCompanion",
      destination: "platform=iOS Simulator,name=iPhone 16,OS=18.0",
      code_coverage: true,
      xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO"
    )
  end

  desc "Format Swift code"
  lane :format do
    sh("../scripts/format.sh")
  end
end
